global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s

rule_files:
  - '/etc/prometheus/pyrra/*.yaml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'jaeger'
    static_configs:
      - targets: [ 'jaeger:14269' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'otel-collector'
    static_configs:
    - targets: [ 'otel-collector:8889' ]
  - job_name: 'fastapi-app'
    static_configs:
    - targets: [ 'fastapi-app:8000' ]
  - job_name: 'flask-app'
    static_configs:
    - targets: [ 'flask-app:9464' ]
  - job_name: 'beyla'
    static_configs:
    - targets: [ 'beyla:8999' ]
  - job_name: 'beyla-internal'
    static_configs:
    - targets: [ 'beyla:8998' ]