# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: TraceID
      httpMethod: POST
    readOnly: false
    editable: true
  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo:3200
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki
      tracesToLogsV2:
        customQuery: true
        query: "{$${__tags}} | trace_id=`$${__trace.traceId}` |= \"\"" # {${__tags}} | trace_id=`${__trace.traceId}` |= ""
        datasourceUid: loki
        filterByTraceID: false
        spanEndTimeShift: "500ms"
        spanStartTimeShift: "-500ms"
        tags:
          - key: "service.name"
            value: "service_name"
      tracesToProfiles:
        customQuery: false
        datasourceUid: "pyroscope"
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
        tags:
          - key: "service.name"
            value: "service_name"
          - key: "http.route"
            value: "endpoint"
    readOnly: false
    editable: true
  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://loki:3100
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      httpMethod: GET
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id"
          matcherType: "label"
          name: Tempo
          url: "$${__value.raw}"
          urlDisplayLabel: 'Tempo'
        # Field with external link
        - matcherRegex: "trace_id"
          matcherType: "label"
          name: Jaeger
          url: 'http://localhost:16686/trace/$${__value.raw}'
          urlDisplayLabel: 'Jaeger'
    readOnly: false
    editable: true
  - uid: jaeger
    orgId: 1
    name: Jaeger
    type: jaeger
    url: http://jaeger:16686/
    access: proxy
    readOnly: false
    editable: true
    # UID should match the datasourceUid in derivedFields.
  - uid: pyroscope
    orgId: 1
    name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    # jsonData:
    #   keepCookies: [pyroscope_git_session]